resources:
  - name: lattice
    type: git
    source:
      uri: https://github.com/cloudfoundry-incubator/lattice.git
      branch: concourse
  - name: diego-release
    type: git
    source:
      uri: https://github.com/cloudfoundry-incubator/diego-release.git
      branch: master
  - name: cf-release
    type: git
    source:
      uri: https://github.com/cloudfoundry/cf-release.git
      branch: runtime-passed
  - name: cf-routing-release
    type: git
    source:
      uri: https://github.com/cloudfoundry-incubator/cf-routing-release.git
      branch: master
  - name: lattice-tar-build
    type: s3
    source:
      bucket: lattice
      regexp: build/lattice-v(.*).tgz
      private: true
      access_key_id: {{aws-access-key-id}}
      secret_access_key: {{aws-secret-access-key}}
  - name: ltc-tar-build
    type: s3
    source:
      bucket: lattice
      regexp: build/ltc-v(.*).tgz
      private: true
      access_key_id: {{aws-access-key-id}}
      secret_access_key: {{aws-secret-access-key}}
  - name: lattice-tar-nightly
    type: s3
    source:
      bucket: lattice
      regexp: nightly/backend/lattice-v(.*).tgz
      private: true
      access_key_id: {{aws-access-key-id}}
      secret_access_key: {{aws-secret-access-key}}
  - name: lattice-bundle-nightly
    type: s3
    source:
      bucket: lattice
      regexp: nightly/lattice-bundle-v(.*).zip
      private: true
      access_key_id: {{aws-access-key-id}}
      secret_access_key: {{aws-secret-access-key}}
  - name: publish-nightly-timer
    type: time
    source:
      start: 18:00 -0500
      stop: 19:00 -0500
      interval: 1h

jobs:
  - name: unit-test-ltc
    plan:
      - get: lattice
        trigger: true
      - task: unit-test-ltc
        file: lattice/concourse/tasks/unit-test-ltc/task.yml
  - name: unit-test-davtool
    plan:
      - get: lattice
        trigger: true
      - task: unit-test-cell-helper
        file: lattice/concourse/tasks/unit-test-cell-helper/task.yml
        config:
          params:
            CELL_HELPER: davtool
  - name: unit-test-s3tool
    plan:
      - get: lattice
        trigger: true
      - task: unit-test-cell-helper
        file: lattice/concourse/tasks/unit-test-cell-helper/task.yml
        config:
          params:
            CELL_HELPER: s3tool
  - name: unit-test-tee2metron
    plan:
      - get: lattice
        trigger: true
      - task: unit-test-cell-helper
        file: lattice/concourse/tasks/unit-test-cell-helper/task.yml
        config:
          params:
            CELL_HELPER: tee2metron

  - name: compile
    plan:
      - aggregate:
        - get: lattice
          trigger: true
          passed:
            - unit-test-ltc
            - unit-test-s3tool
            - unit-test-tee2metron
        - get: diego-release
        - get: cf-release
        - get: cf-routing-release
      - aggregate:
        - task: compile-lattice-tar
          file: lattice/concourse/tasks/compile-lattice-tar/task.yml
        - task: compile-ltc
          file: lattice/concourse/tasks/compile-ltc/task.yml
      - aggregate:
        - put: lattice-tar-build
          params:
            from: lattice/build/lattice-v(.*).tgz
            to: /build/
        - put: ltc-tar-build
          params:
            from: lattice/build/ltc-v(.*).tgz
            to: /build/

  - name: cluster-test-vagrant-aws
    plan:
      - aggregate:
        - get: lattice
          trigger: true
          passed: [compile]
        - get: lattice-tar-build
          passed: [compile]
        - get: ltc-tar-build
          passed: [compile]
      - task: cluster-test-vagrant-aws
        file: lattice/concourse/tasks/cluster-test-vagrant-aws/task.yml
        config:
          params:
            AWS_ACCESS_KEY_ID: {{aws-access-key-id}}
            AWS_SECRET_ACCESS_KEY: {{aws-secret-access-key}}
            AWS_SSH_PRIVATE_KEY: {{aws-ssh-private-key}}
        ensure:
          task: cleanup-cluster-test-vagrant-aws
          file: lattice/concourse/tasks/cleanup-cluster-test-vagrant-aws/task.yml
          config:
            params:
              AWS_ACCESS_KEY_ID: {{aws-access-key-id}}
              AWS_SECRET_ACCESS_KEY: {{aws-secret-access-key}}
              AWS_SSH_PRIVATE_KEY: {{aws-ssh-private-key}}

  - name: cluster-test-terraform-aws
    plan:
      - aggregate:
        - get: lattice
          trigger: true
          passed: [compile]
        - get: lattice-tar-build
          passed: [compile]
        - get: ltc-tar-build
          passed: [compile]
      - task: cluster-test-terraform-aws
        file: lattice/concourse/tasks/cluster-test-terraform-aws/task.yml
        config:
          params:
            AWS_ACCESS_KEY_ID: {{aws-access-key-id}}
            AWS_SECRET_ACCESS_KEY: {{aws-secret-access-key}}
            AWS_SSH_PRIVATE_KEY: {{aws-ssh-private-key}}
            AWS_SSH_PRIVATE_KEY_NAME: {{aws-ssh-private-key-name}}
        ensure:
          task: cleanup-cluster-test-terraform-aws
          file: lattice/concourse/tasks/cleanup-cluster-test-terraform-aws/task.yml

  - name: cluster-test-terraform-gce
    plan:
      - aggregate:
        - get: lattice
          passed: [compile]
          trigger: true
        - get: lattice-tar-build
          passed: [compile]
        - get: ltc-tar-build
          passed: [compile]
      - task: cluster-test-terraform-gce
        file: lattice/concourse/tasks/cluster-test-terraform-gce/task.yml
        config:
          params:
            GCE_SSH_PRIVATE_KEY: {{gce-ssh-private-key}}
            GCE_PROJECT_NAME: {{gce-project-name}}
            GCE_ACCOUNT_FILE_JSON: {{gce-account-file-json}}
        ensure:
          task: cleanup-cluster-test-terraform-gce
          file: lattice/concourse/tasks/cleanup-cluster-test-terraform-gce/task.yml

  - name: publish-nightly
    plan:
      - get: publish-nightly-timer
        trigger: true
      - aggregate:
        - get: lattice
          passed:
          - cluster-test-vagrant-aws
          - cluster-test-terraform-aws
          - cluster-test-terraform-gce
        - get: lattice-tar-build
          passed:
          - cluster-test-vagrant-aws
          - cluster-test-terraform-aws
          - cluster-test-terraform-gce
        - get: ltc-tar-build
          passed:
          - cluster-test-vagrant-aws
          - cluster-test-terraform-aws
          - cluster-test-terraform-gce
      - aggregate:
        - task: generate-terraform-templates
          file: lattice/concourse/tasks/generate-terraform-templates/task.yml
          config:
            params:
              S3_LATTICE_PATH: lattice/nightly
        - task: generate-vagrantfile
          file: lattice/concourse/tasks/generate-vagrantfile/task.yml
          config:
            params:
              S3_LATTICE_PATH: lattice/nightly
      - task: compile-lattice-bundles
        file: lattice/concourse/tasks/compile-lattice-bundles/task.yml
      - aggregate:
        - put: lattice-tar-nightly
          params:
            from: lattice-tar-build/lattice-v(.*).tgz
            to: /nightly/backend/
        - put: lattice-tar-nightly
          params:
            from: lattice-tar-build/lattice-v(.*).tgz
            to: /nightly/backend/lattice-latest.tgz
        - put: lattice-bundle-nightly
          params:
            from: compile-lattice-bundles/lattice-bundle-v(.*)-linux.zip
            to: /nightly/
        - put: lattice-bundle-nightly
          params:
            from: compile-lattice-bundles/lattice-bundle-v(.*)-linux.zip
            to: /nightly/lattice-bundle-latest-linux.zip
        - put: lattice-bundle-nightly
          params:
            from: compile-lattice-bundles/lattice-bundle-v(.*)-osx.zip
            to: /nightly/
        - put: lattice-bundle-nightly
          params:
            from: compile-lattice-bundles/lattice-bundle-v(.*)-osx.zip
            to: /nightly/lattice-bundle-latest-osx.zip
