branches:
  only:
    - master

language: go
go:
- 1.4
- 1.5

matrix:
  allow_failures:
    - go: 1.5

before_install:
- go get -v golang.org/x/tools/cmd/cover
- go get -v github.com/onsi/ginkgo/ginkgo
- go get -v github.com/mattn/goveralls
- export GOPATH=$PWD/ltc/Godeps/_workspace:$GOPATH
- export PATH=$HOME/gopath/bin:$PATH

script:
- ginkgo -r --randomizeAllSpecs --failOnPending --skipMeasurements --cover ltc cell-helpers
- test -z "$(go fmt ./ltc/... ./cell-helpers/...)"

after_success:
- 'echo "mode: set" > coverage.out'
- 'find ltc cell-helpers -name "*.coverprofile" -exec grep -v mode: {} >> coverage.out \;'
- goveralls -coverprofile=coverage.out -repotoken=$COVERALLS_TOKEN

